on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  sonarcloud:
    name: Run Sonar analysis
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
